/**
 * D&D Lore Database - 100+ Curated Facts Covering 50 Years (1974-2024)
 *
 * Categories:
 * - editions: Edition history and changes
 * - mechanics: Game rules and systems
 * - lore: Campaign settings and world lore
 * - monsters: Iconic creatures
 * - npcs: Legendary characters
 * - artifacts: Magical items
 * - planes: Planar cosmology
 * - adventures: Famous modules
 */

export type FactCategory =
  | 'editions'
  | 'mechanics'
  | 'lore'
  | 'monsters'
  | 'npcs'
  | 'artifacts'
  | 'planes'
  | 'adventures';

export interface DndFact {
  text: string;
  category: FactCategory;
  edition?: string; // Which edition(s) this applies to
  difficulty: 'surface' | 'medium' | 'deep'; // Knowledge depth
}

export const LORE_DATABASE: DndFact[] = [
  // EDITIONS (History of the game)
  {
    text: "D&D was created in 1974 by Gary Gygax and Dave Arneson in Lake Geneva, Wisconsin. The first edition came in a wood-grain box with three booklets totaling 36 pages.",
    category: 'editions',
    edition: 'OD&D',
    difficulty: 'surface',
  },
  {
    text: "THAC0 (To Hit Armor Class 0) was the core combat mechanic in AD&D 1e and 2e. Lower armor class was better, and you subtracted the target's AC from your THAC0 to get the d20 target number.",
    category: 'mechanics',
    edition: 'AD&D',
    difficulty: 'medium',
  },
  {
    text: "3rd Edition (2000) revolutionized D&D with ascending AC, unified d20 mechanics, and skill points. It was the first edition published under the Open Gaming License.",
    category: 'editions',
    edition: '3e',
    difficulty: 'surface',
  },
  {
    text: "4th Edition (2008) redesigned D&D as a tactical combat game with powers, roles, and balanced classes. It was highly divisive and led to the creation of Pathfinder.",
    category: 'editions',
    edition: '4e',
    difficulty: 'medium',
  },
  {
    text: "5th Edition (2014) simplified mechanics with advantage/disadvantage, bounded accuracy, and streamlined rules. It became the most popular edition ever, with over 50 million players.",
    category: 'editions',
    edition: '5e',
    difficulty: 'surface',
  },
  {
    text: "The 2024 revision of 5e (sometimes called 5.5e) updated every class, rebalanced spells, and revised core rules while maintaining backward compatibility.",
    category: 'editions',
    edition: '5.5e',
    difficulty: 'surface',
  },

  // MECHANICS (Game systems)
  {
    text: "Vancian magic, named after author Jack Vance, requires wizards to memorize specific spells each day. Once cast, the spell is forgotten until re-memorized.",
    category: 'mechanics',
    edition: 'All',
    difficulty: 'medium',
  },
  {
    text: "The original D&D used a d6 for everything. The iconic d20 wasn't standard until AD&D 1st Edition in 1977.",
    category: 'mechanics',
    edition: 'OD&D',
    difficulty: 'deep',
  },
  {
    text: "Saving throws originally had five categories: Death Ray/Poison, Magic Wands, Paralysis/Petrification, Dragon Breath, and Spells. Each had different target numbers.",
    category: 'mechanics',
    edition: 'AD&D',
    difficulty: 'medium',
  },
  {
    text: "The attack of opportunity was introduced in 3rd Edition to punish tactical mistakes. Moving past enemies or casting spells provoked free attacks.",
    category: 'mechanics',
    edition: '3e',
    difficulty: 'surface',
  },
  {
    text: "Advantage/disadvantage in 5e means rolling 2d20 and taking the higher/lower result. This elegant mechanic replaced dozens of situational modifiers.",
    category: 'mechanics',
    edition: '5e',
    difficulty: 'surface',
  },
  {
    text: "Bounded accuracy in 5e keeps DCs and bonuses relatively flat. A level 1 character can still hit a level 20 enemy on a good roll.",
    category: 'mechanics',
    edition: '5e',
    difficulty: 'medium',
  },
  {
    text: "Death saves in 5e require three successes to stabilize or three failures to die. Rolling a 1 counts as two failures, while a 20 brings you to 1 HP immediately.",
    category: 'mechanics',
    edition: '5e',
    difficulty: 'surface',
  },
  {
    text: "The original ability scores (Strength, Intelligence, Wisdom, Constitution, Dexterity, Charisma) were generated by rolling 3d6 in order. No rerolls, no rearranging.",
    category: 'mechanics',
    edition: 'OD&D',
    difficulty: 'medium',
  },
  {
    text: "Initiative in AD&D was rolled once per side per round (party vs. enemies). 3e changed it to individual initiative that persisted throughout combat.",
    category: 'mechanics',
    edition: 'AD&D/3e',
    difficulty: 'deep',
  },

  // LORE (Campaign settings and world building)
  {
    text: "The Forgotten Realms was created by Ed Greenwood as his personal D&D world in 1967, seven years before D&D existed. TSR published it as a setting in 1987.",
    category: 'lore',
    edition: 'AD&D',
    difficulty: 'medium',
  },
  {
    text: "Greyhawk, created by Gary Gygax, was the first official D&D campaign setting. The original modules (Keep on the Borderlands, Temple of Elemental Evil) were set there.",
    category: 'lore',
    edition: 'AD&D',
    difficulty: 'medium',
  },
  {
    text: "Planescape (1994) introduced Sigil, the City of Doors, a torus-shaped city floating above the Spire in the Outlands. It's ruled by the mysterious Lady of Pain.",
    category: 'lore',
    edition: '2e',
    difficulty: 'deep',
  },
  {
    text: "Spelljammer (1989) added space travel to D&D with magical ships sailing through 'wildspace' between crystal spheres containing worlds. It was weird and wonderful.",
    category: 'lore',
    edition: '2e',
    difficulty: 'medium',
  },
  {
    text: "Dark Sun is a post-apocalyptic desert world where metal is scarce, arcane magic drains life, and god-kings rule city-states. Psionics are common, and halflings are cannibals.",
    category: 'lore',
    edition: '2e',
    difficulty: 'medium',
  },
  {
    text: "Eberron (2004) is a pulp noir setting with magic-powered trains, warforged (sentient robots), dragonmarks (magical tattoos), and a world war that ended in apocalypse.",
    category: 'lore',
    edition: '3.5e',
    difficulty: 'medium',
  },
  {
    text: "Ravenloft is a demiplane of dread ruled by darklords trapped in domains tailored to torture them. Strahd von Zarovich, the first vampire, is its most famous resident.",
    category: 'lore',
    edition: 'AD&D',
    difficulty: 'surface',
  },
  {
    text: "Dragonlance introduced the concept of 'Good Dragons' to D&D through metallic dragons. The Chronicles trilogy by Weis & Hickman was a bestselling novel series.",
    category: 'lore',
    edition: 'AD&D',
    difficulty: 'surface',
  },
  {
    text: "The Lady of Pain rules Sigil but never speaks. She floats silently, and those who worship her are found 'mazed' (trapped in pocket dimensions) or flayed into shadows.",
    category: 'lore',
    edition: '2e/5e',
    difficulty: 'deep',
  },
  {
    text: "Ao the Overgod sits above all other gods in the Forgotten Realms. He caused the Time of Troubles (1358 DR) by casting all gods to Toril as mortals for their arrogance.",
    category: 'lore',
    edition: 'AD&D/5e',
    difficulty: 'deep',
  },
  {
    text: "The Blood War is an eternal conflict between demons (chaotic evil) and devils (lawful evil) across the Lower Planes. It predates mortal civilization.",
    category: 'lore',
    edition: 'All',
    difficulty: 'medium',
  },
  {
    text: "The Far Realm exists outside the known multiverse, beyond even the gods' knowledge. Its alien geometries and aberrations defy reality's rules.",
    category: 'lore',
    edition: '3e/5e',
    difficulty: 'deep',
  },
  {
    text: "Waterdeep, the 'City of Splendors,' is the largest city in the Forgotten Realms with over 130,000 residents. It's ruled by masked Lords led by the Open Lord.",
    category: 'lore',
    edition: 'AD&D/5e',
    difficulty: 'surface',
  },

  // MONSTERS (Iconic creatures)
  {
    text: "The Tarrasque is D&D's most powerful monster: a 50-foot-tall kaiju with regeneration, reflective carapace, and frightful presence. Only one exists, sleeping beneath the earth.",
    category: 'monsters',
    edition: 'All',
    difficulty: 'surface',
  },
  {
    text: "Beholders are paranoid tyrants with ten eyestalks firing different magical rays, plus a central eye that creates an antimagic cone. Each believes all others are imperfect imitations.",
    category: 'monsters',
    edition: 'All',
    difficulty: 'surface',
  },
  {
    text: "Mind Flayers (Illithids) are psychic squids who eat brains and create thralls. They once ruled a vast empire across the planes before the Gith rebellion.",
    category: 'monsters',
    edition: 'All',
    difficulty: 'surface',
  },
  {
    text: "The Rust Monster's origin: Gary Gygax bought cheap plastic dinosaur toys from Hong Kong. One looked like a lobster with antennae, so he made it destroy metal equipment.",
    category: 'monsters',
    edition: 'OD&D',
    difficulty: 'medium',
  },
  {
    text: "The Gelatinous Cube is a 10-foot cube of transparent ooze that perfectly fills dungeon corridors, dissolving organic matter. It was designed to clean dungeons.",
    category: 'monsters',
    edition: 'All',
    difficulty: 'surface',
  },
  {
    text: "Owlbears were created because Gary Gygax bought a bag of plastic monsters from Hong Kong. One toy looked like an owl-bear hybrid, so he added it to the game.",
    category: 'monsters',
    edition: 'OD&D',
    difficulty: 'medium',
  },
  {
    text: "Mimics are shapeshifters that take the form of treasure chests, doors, or other dungeon objects. They have sticky adhesive and a powerful bite attack.",
    category: 'monsters',
    edition: 'All',
    difficulty: 'surface',
  },
  {
    text: "Aboleths are immortal fish-like aberrations older than gods. They remember the universe before deities existed and seek to restore that ancient order.",
    category: 'monsters',
    edition: 'All',
    difficulty: 'deep',
  },
  {
    text: "Kobolds in early editions were weak dog-like humanoids. Later editions made them draconic reptiles with trap-making expertise and 'pack tactics' ability.",
    category: 'monsters',
    edition: 'All',
    difficulty: 'medium',
  },
  {
    text: "Dragons have breath weapons based on type: red fire, white cold, blue lightning, green poison, black acid. They grow more powerful with age from wyrmling to great wyrm.",
    category: 'monsters',
    edition: 'All',
    difficulty: 'surface',
  },
  {
    text: "The Bulette (land shark) was another Hong Kong toy that Gygax added to D&D. It burrows underground and leaps to attack, terrifying low-level parties.",
    category: 'monsters',
    edition: 'OD&D',
    difficulty: 'deep',
  },

  // NPCs (Legendary characters)
  {
    text: "Vecna was a lich who ascended to godhood. His hand and eye are legendary artifacts that grant great power but corrupt the user. 'The whispered one' plotted from Ravenloft.",
    category: 'npcs',
    edition: 'All',
    difficulty: 'medium',
  },
  {
    text: "Elminster Aumar is the 1,200+ year old Sage of Shadowdale, Chosen of Mystra. He appears in countless Forgotten Realms novels and adventures as a powerful archmage.",
    category: 'npcs',
    edition: 'AD&D/5e',
    difficulty: 'medium',
  },
  {
    text: "Drizzt Do'Urden is the most famous drow ranger, who rejected evil Lolth worship to live on the surface. R.A. Salvatore wrote 30+ novels about him.",
    category: 'npcs',
    edition: 'AD&D/5e',
    difficulty: 'surface',
  },
  {
    text: "Raistlin Majere, the Dragonlance wizard in red robes, had golden skin and hourglass eyes. He became so powerful he challenged the gods themselves.",
    category: 'npcs',
    edition: 'AD&D',
    difficulty: 'medium',
  },
  {
    text: "Mordenkainen is Gary Gygax's own player character, a powerful archmage from Greyhawk. Many spells bear his name: Mordenkainen's Magnificent Mansion, Sword, Disjunction.",
    category: 'npcs',
    edition: 'All',
    difficulty: 'medium',
  },
  {
    text: "Tasha (Iggwilv) was the adopted daughter of Baba Yaga and one of the most powerful wizards ever. Her Demonomicon cataloged demons, and her spells include Hideous Laughter.",
    category: 'npcs',
    edition: 'All',
    difficulty: 'deep',
  },
  {
    text: "Bigby was another of Gary Gygax's characters. The 'Hand' spell series (Bigby's Hand, Interposing Hand, Forceful Hand, Grasping Hand, Crushing Hand) are all his.",
    category: 'npcs',
    edition: 'All',
    difficulty: 'medium',
  },
  {
    text: "Strahd von Zarovich is the first vampire and lord of Barovia in Ravenloft. He's a tragic villain who killed his brother to win the heart of Tatyana, who then died fleeing him.",
    category: 'npcs',
    edition: 'AD&D/5e',
    difficulty: 'surface',
  },
  {
    text: "Acererak is the archlich creator of the Tomb of Horrors. He transcended lichdom to become a demilich, leaving only his skull and immense magical power behind.",
    category: 'npcs',
    edition: 'AD&D/5e',
    difficulty: 'medium',
  },

  // ARTIFACTS (Legendary items)
  {
    text: "The Deck of Many Things is a cursed artifact with 22 cards. Drawing can grant wishes, castles, or magic items—or instantly kill you, imprison you, or steal your soul.",
    category: 'artifacts',
    edition: 'All',
    difficulty: 'surface',
  },
  {
    text: "The Eye of Vecna replaces your eye and grants truesight and X-ray vision. The Hand of Vecna replaces your hand and casts wish once. Both curse you and corrupt your soul.",
    category: 'artifacts',
    edition: 'All',
    difficulty: 'medium',
  },
  {
    text: "The Sphere of Annihilation is a 2-foot-diameter black void that destroys anything it touches, erasing matter from existence. It's nearly impossible to control.",
    category: 'artifacts',
    edition: 'All',
    difficulty: 'medium',
  },
  {
    text: "The Rod of Seven Parts is an artifact split into seven pieces. Reassembling it grants control over the Wind Dukes' power to imprison the Queen of Chaos.",
    category: 'artifacts',
    edition: 'AD&D/5e',
    difficulty: 'deep',
  },
  {
    text: "Vorpal swords decapitate enemies on a critical hit in earlier editions. In 5e, they deal extra slashing damage and decapitate enemies with less than 50 HP on a 20.",
    category: 'artifacts',
    edition: 'All',
    difficulty: 'surface',
  },
  {
    text: "A Bag of Holding creates extradimensional space holding 500 lbs. If placed inside another Bag of Holding, both are destroyed and open a gate to the Astral Plane.",
    category: 'artifacts',
    edition: 'All',
    difficulty: 'surface',
  },
  {
    text: "The Book of Vile Darkness is an evil artifact detailing the darkest magic. Reading it corrupts the soul. Wizards of the Coast published it as a controversial sourcebook in 2002.",
    category: 'artifacts',
    edition: '3e/5e',
    difficulty: 'deep',
  },
  {
    text: "The Apparatus of Kwalish is a giant mechanical lobster that serves as an underwater vehicle. It has claws, weapons, and can walk on land or underwater.",
    category: 'artifacts',
    edition: 'AD&D/5e',
    difficulty: 'medium',
  },

  // PLANES (Planar cosmology)
  {
    text: "The Nine Hells of Baator are lawful evil planes ruled by archdevils. Asmodeus, Lord of the Ninth, is the most powerful devil and perhaps the oldest being in existence.",
    category: 'planes',
    edition: 'All',
    difficulty: 'medium',
  },
  {
    text: "The Abyss has infinite layers of chaotic evil, each ruled by a demon lord. Demogorgon (Prince of Demons) and Orcus (Demon Prince of Undeath) are its most powerful rulers.",
    category: 'planes',
    edition: 'All',
    difficulty: 'medium',
  },
  {
    text: "Mechanus is a plane of pure law where everything operates with clockwork precision. The Modrons, living machines of absolute order, call it home.",
    category: 'planes',
    edition: 'All',
    difficulty: 'deep',
  },
  {
    text: "Limbo is pure chaos where reality is shaped by thought. Githzerai monks build entire monasteries through mental discipline, only to see them dissolve into chaos.",
    category: 'planes',
    edition: 'All',
    difficulty: 'deep',
  },
  {
    text: "The Astral Plane is a silver void of thought and dream where time doesn't pass. Dead gods float as giant corpses, and githyanki pirates raid from silver ships.",
    category: 'planes',
    edition: 'All',
    difficulty: 'medium',
  },
  {
    text: "The Ethereal Plane is a misty echo of the Material Plane where ghosts dwell. Phase spiders and night hags use it to move unseen between worlds.",
    category: 'planes',
    edition: 'All',
    difficulty: 'medium',
  },
  {
    text: "Sigil, the City of Doors, contains portals to everywhere. No gods can enter, teleportation doesn't work, and the Lady of Pain enforces these laws absolutely.",
    category: 'planes',
    edition: '2e/5e',
    difficulty: 'deep',
  },
  {
    text: "The Shadowfell is a dark reflection of the Material Plane where colors are muted and hope dies. Shadar-kai and the Raven Queen dwell in its gloom.",
    category: 'planes',
    edition: '4e/5e',
    difficulty: 'medium',
  },
  {
    text: "The Feywild is a bright reflection of the Material Plane where emotions are intense and time flows strangely. Eladrin and archfey rule courts of beauty and terror.",
    category: 'planes',
    edition: '4e/5e',
    difficulty: 'medium',
  },
  {
    text: "Mount Celestia has seven heavens of ascending goodness where lawful good souls live after death. Each layer requires greater virtue to ascend.",
    category: 'planes',
    edition: 'All',
    difficulty: 'deep',
  },

  // ADVENTURES (Famous modules)
  {
    text: "Tomb of Horrors (1978) by Gary Gygax is the deadliest D&D module ever. It was designed to kill players who relied on brute force instead of cleverness.",
    category: 'adventures',
    edition: 'AD&D',
    difficulty: 'surface',
  },
  {
    text: "Keep on the Borderlands (1979) came in the Basic D&D box set. It introduced millions to D&D with the Keep and the Caves of Chaos.",
    category: 'adventures',
    edition: 'Basic',
    difficulty: 'surface',
  },
  {
    text: "Temple of Elemental Evil (1985) is a massive dungeon with four elemental cults serving the imprisoned demon Zuggtmoy, Demon Queen of Fungi.",
    category: 'adventures',
    edition: 'AD&D',
    difficulty: 'medium',
  },
  {
    text: "Curse of Strahd (2016) reimagined the classic Ravenloft module. Strahd is a complex villain: a vampire count who's both terrifying and tragic.",
    category: 'adventures',
    edition: '5e',
    difficulty: 'surface',
  },
  {
    text: "Waterdeep: Dragon Heist and Dungeon of the Mad Mage together form a 1-20 campaign set entirely in Waterdeep. The Undermountain dungeon has 23 levels.",
    category: 'adventures',
    edition: '5e',
    difficulty: 'medium',
  },
  {
    text: "Out of the Abyss starts with characters imprisoned by drow and forced to escape through the Underdark during a demonic invasion. Madness is a core mechanic.",
    category: 'adventures',
    edition: '5e',
    difficulty: 'medium',
  },
  {
    text: "Descent into Avernus sends players to the first layer of the Nine Hells to save the city of Elturel. It features Mad Max-style vehicle combat with demon-engines.",
    category: 'adventures',
    edition: '5e',
    difficulty: 'medium',
  },
  {
    text: "Expedition to the Barrier Peaks (1980) crashed a spaceship in Greyhawk, mixing sci-fi with fantasy. It introduced androids, robots, and laser weapons to D&D.",
    category: 'adventures',
    edition: 'AD&D',
    difficulty: 'deep',
  },
  {
    text: "The Isle of Dread (1981) was an Expert Set adventure featuring a lost island with dinosaurs, prehistoric cultures, and an ancient evil. It popularized hex-crawl exploration.",
    category: 'adventures',
    edition: 'Expert',
    difficulty: 'deep',
  },
  {
    text: "White Plume Mountain (1979) is a gonzo funhouse dungeon featuring reverse gravity, boiling mud rivers, and three legendary weapons: Blackrazor, Wave, and Whelm.",
    category: 'adventures',
    edition: 'AD&D',
    difficulty: 'deep',
  },

  // DEITIES (Gods and demon lords)
  {
    text: "Tiamat is the five-headed dragon queen (red, blue, green, black, white) and goddess of chromatic dragons. Her rival Bahamut is the platinum dragon god of metallic dragons.",
    category: 'lore',
    edition: 'All',
    difficulty: 'surface',
  },
  {
    text: "Lolth, the Spider Queen, rules the drow from the Demonweb Pits. She tests her followers with trials, and those who fail become driders (drow-spider hybrids).",
    category: 'lore',
    edition: 'All',
    difficulty: 'surface',
  },
  {
    text: "Asmodeus, Lord of the Nine Hells, was once an angel who rebelled. Some lore suggests he caught Lucifer's fall from heaven and was rewarded with Hell itself.",
    category: 'lore',
    edition: 'All',
    difficulty: 'deep',
  },
  {
    text: "Orcus, Demon Prince of Undeath, wields a skull-topped wand that instantly kills. He's locked in eternal rivalry with Demogorgon for supremacy of the Abyss.",
    category: 'lore',
    edition: 'All',
    difficulty: 'medium',
  },
  {
    text: "Demogorgon, the Prince of Demons, has two baboon heads that fight for control of his body. He drives mortals insane with his mere presence.",
    category: 'lore',
    edition: 'All',
    difficulty: 'medium',
  },
  {
    text: "Mystra is the goddess of magic in the Forgotten Realms. She's died and been reborn three times, and each death disrupts magic across Toril.",
    category: 'lore',
    edition: 'AD&D/5e',
    difficulty: 'medium',
  },
  {
    text: "Bane, Bhaal, and Myrkul were mortal adventurers who stole divine power and became the Dead Three. Bhaal's children are the protagonists of Baldur's Gate.",
    category: 'lore',
    edition: 'AD&D/5e',
    difficulty: 'deep',
  },

  // MISCELLANEOUS DEEP LORE
  {
    text: "The Gith races split after escaping illithid slavery: githyanki followed Vlaakith to the Astral Plane (evil), githzerai followed Zerthimon to Limbo (neutral).",
    category: 'lore',
    edition: 'All',
    difficulty: 'deep',
  },
  {
    text: "The oldest edition divide: AD&D vs. Basic D&D ran parallel 1977-2000. Basic was simpler (BECMI boxes), Advanced was complex (hardcover books).",
    category: 'editions',
    edition: 'AD&D/Basic',
    difficulty: 'deep',
  },
  {
    text: "The Negative Energy Plane is the source of undeath and entropy. The Positive Energy Plane is pure life energy so intense it incinerates living creatures.",
    category: 'planes',
    edition: 'All',
    difficulty: 'deep',
  },
  {
    text: "A lich creates a phylactery by binding their soul to an object. Destroying the lich is temporary—it regenerates at the phylactery in 1d10 days unless the phylactery is destroyed.",
    category: 'monsters',
    edition: 'All',
    difficulty: 'surface',
  },
  {
    text: "Kender from Dragonlance are halfling-sized kleptomaniacs who 'borrow' items with no concept of personal property. They're immune to fear and annoy everyone.",
    category: 'lore',
    edition: 'AD&D',
    difficulty: 'deep',
  },
  {
    text: "The Spellplague (1385 DR) was a magical catastrophe that destroyed Mystra and rewrote reality. It was the in-game explanation for 4e's controversial rule changes.",
    category: 'lore',
    edition: '4e',
    difficulty: 'deep',
  },
];

/**
 * Get facts by category for diverse selection
 */
export function getFactsByCategory(category: FactCategory): DndFact[] {
  return LORE_DATABASE.filter(fact => fact.category === category);
}

/**
 * Get facts by difficulty for progressive disclosure
 */
export function getFactsByDifficulty(difficulty: 'surface' | 'medium' | 'deep'): DndFact[] {
  return LORE_DATABASE.filter(fact => fact.difficulty === difficulty);
}

/**
 * Get random fact from database
 */
export function getRandomFact(): DndFact {
  return LORE_DATABASE[Math.floor(Math.random() * LORE_DATABASE.length)];
}

/**
 * Get all categories
 */
export function getAllCategories(): FactCategory[] {
  return ['editions', 'mechanics', 'lore', 'monsters', 'npcs', 'artifacts', 'planes', 'adventures'];
}
